# Loads default set of integrations. Do not remove.
default_config:

# Enable Cloud
cloud:

# Load frontend themes from the themes folder
frontend:
  #themes: !include_dir_merge_named themes

# Sleep Number Bed
sleepiq:
  username: !secret sleepnumber_uid
  password: !secret sleepnumber_pswrd

# Ecovac
ecovacs:
  username: !secret ecovac_uid
  password: !secret ecovac_pswrd
  country: us
  continent: ww

# Spotcast
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: SE #optional, added in 3.6.24

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include templates.yaml

# Logging Code
system_log:
  fire_event: true

zha:
  zigpy_config:
    ota:
      ikea_provider: false
      ledvance_provider: false
      otau_directory: /config/peanutplugfirmware
logger:
  default: info
  logs:
    homeassistant.core: warning
    homeassistant.components.zha: debug
    #bellows.zigbee.application: info
    #bellows.ezsp: info
    #zigpy: debug
    #zigpy_cc: info
    #zigpy_deconz.zigbee.application: info
    #zigpy_deconz.api: info
    #zigpy_xbee.zigbee.application: info
    #zigpy_xbee.api: info
    #zigpy_zigate: info
    #zigpy_znp: info
    #zhaquirks: info

# pfSense Config
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.3.1 # This needs to be set to the IP of your reverse proxy
    - 192.168.2.1
    - 192.168.1.33
    - 192.168.4.1
    - 192.168.4.10
    - 97.75.141.168
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22
