substitutions:
  # change device name to match your desired name
  device_name: "office-fall-sensor"
  # change sensor name below to the one you want to see in Home Assistant
  device_name_pretty: Office Fall Sensor
  # change room name below to the one you want to see in Home Assistant
  room: ""
  # change the below to be your WiFi SSID
  ssid: !secret wifi_ssid
  # change the below to be your WiFi password
  wifi_password: !secret wifi_password
  # UART TX Pin
  uart_tx_pin: "1"
  # UART RX Pin
  uart_rx_pin: "3"
esphome:
  name: $device_name
  includes:
    - header/esp-mmwave-60ghz-fda-sensor.h
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"  # Override, defaults to '-DARDUINO_USB_CDC_ON_BOOT=1'
  friendly_name: $device_name_pretty

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    sensor: INFO
  #level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "5WpdMlX8MrAX6PMTWpN7Ua6jo3Vhnk7okM0oRavqVI4="

ota:
  password: "0c9fa2ff2e9c4c004e580f9c0a3ede68"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.3.25

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office-Fall-Sensor"
    password: "Chozn@5826"

captive_portal:

#esp32_ble_tracker:
#  id: office_tracker
#  
#  on_ble_advertise:
#    - mac_address:
        
#      then:
#        - lambda: |-
#            ESP_LOGD("ble_adv", "New BLE device");
#            ESP_LOGD("ble_adv", "  address: %s", x.address_str().c_str());
#            ESP_LOGD("ble_adv", "  name: %s", x.get_name().c_str());
#            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
#            for (auto uuid : x.get_service_uuids()) {
#                ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
#            }
#            ESP_LOGD("ble_adv", "  Advertised service data:");
#            for (auto data : x.get_service_datas()) {
#                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
#            }
#            ESP_LOGD("ble_adv", "  Advertised manufacturer data:");
#            for (auto data : x.get_manufacturer_datas()) {
#                ESP_LOGD("ble_adv", "    - %s: (length %i)", data.uuid.to_string().c_str(), data.data.size());
#            }

web_server:
  port: 80
  version: 2
  include_internal: true

http_request:
  useragent: esphome/$device_name
  timeout: 2s
  
uart:
  id: uart_bus
  tx_pin: ${uart_tx_pin}
  rx_pin: ${uart_rx_pin}
  baud_rate: 115200

sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new UARTSensor(id(uart_bus)); 
      App.register_component(my_sensor);
      return {my_sensor->activity_sensor, my_sensor->presence_sensor, my_sensor->motion_sensor, my_sensor->fall_sensor, my_sensor->fall_det_sw, my_sensor->fall_det_sens};
  
    sensors:
      - name: "${room} Activity Level"
        state_class: measurement
      - id: presence_sensor
        name: "internal_presense_sensor_to_binary_template"
        internal: true
        on_value:
          - binary_sensor.template.publish:
              id: presence_template
              state: !lambda return x > 0;
      - id: motion_sensor
        name: "internal_motion_sensor_to_binary_template"
        internal: true
        on_value:
          - binary_sensor.template.publish:
              id: motion_template
              state: !lambda return x > 0;
      - id: fall_sensor
        name: "internal_fall_sensor_to_binary_template"
        internal: true
        on_value:
          - binary_sensor.template.publish:
              id: fall_template
              state: !lambda return x > 0;
      - id: fall_det_sw
        name: "internal_fall_det_sw_to_binary_template"
        internal: true
        on_value:
          - switch.template.publish:
              id: fall_det_sw_template
              state: !lambda return x > 0;
      - id: fall_det_sens
        name: "internal_fall_det_sens_to_binary_template"
        internal: true

   # RSSI based on MAC address
#  - platform: ble_rssi
#    mac_address: 94:45:60:9F:F7:00
#    name: "Juan's Pixel Watch"


button:
  - platform: restart
    name: "Restart MCU: ${room}"
    entity_category: diagnostic
    on_press:
      - uart.write:
          id: uart_bus
          data: "resetSystem 0"
  - platform: template
    name: "Reset Radar Module: ${room}"
    id: reset_radar_module
    entity_category: diagnostic
    on_press:
      - uart.write: [0x53, 0x59, 0x01, 0x02, 0x00, 0x01, 0x0F, 0xBF, 0x54, 0x43]

switch:
  - platform: template
    name: Fall Detection Switch
    id: fall_det_sw_template
    entity_category: config
    optimistic: false
    turn_on_action:
      - uart.write: [0x53, 0x59, 0x83, 0x00, 0x00, 0x01, 0x01, 0x31, 0x54, 0x43]
    turn_off_action:
      - uart.write: [0x53, 0x59, 0x83, 0x00, 0x00, 0x01, 0x00, 0x30, 0x54, 0x43]

number:
  - platform: template
    name: Fall Detection Sensitivity
    id: fall_det_sens_template
    entity_category: config
    min_value: 0
    max_value: 3
    lambda: |-
      return id(fall_det_sens).state;
    step: 1
    set_action:
    - if:
        condition:
          lambda: 'return (int)x == 0.000000;'
        then:
          - uart.write: [0x53, 0x59, 0x83, 0x0D, 0x00, 0x01, 0x00, 0x3D, 0x54, 0x43]
    - if:
        condition:
          lambda: 'return (int)x == 1.000000;'
        then:
          - uart.write: [0x53, 0x59, 0x83, 0x0D, 0x00, 0x01, 0x01, 0x3E, 0x54, 0x43]
    - if:
        condition:
          lambda: 'return (int)x == 2.000000;'
        then:
          - uart.write: [0x53, 0x59, 0x83, 0x0D, 0x00, 0x01, 0x02, 0x3F, 0x54, 0x43]
    - if:
        condition:
          lambda: 'return (int)x == 3.000000;'
        then:
          - uart.write: [0x53, 0x59, 0x83, 0x0D, 0x00, 0x01, 0x03, 0x40, 0x54, 0x43]

binary_sensor:
  - platform: template
    id: presence_template
    name: "${room} Presence"
    device_class: occupancy
    filters:
      - delayed_off: 5s
  - platform: template
    id: motion_template
    name: "${room} Motion"
    device_class: motion
  - platform: template
    id: fall_template
    name: "${room} Fall Detection"
    device_class: safety
#  - platform: ble_presence
#    mac_address: 94:45:60:9F:F7:00
#    name: "Juan's Pixel Watch"
    